version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/audiobook
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audiobook
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: 